test_that("manual_logistic_regression works", {
  set.seed(2022)
  x1 = rnorm(30,3,2) + 0.1*c(1:30)
  x2 = rbinom(30,1,0.3)
  x3 = rpois(n = 30, lambda = 4)
  x3[16:30] = x3[16:30] - rpois(n = 15, lambda = 2)
  x = cbind(x1,x2,x3)
  y = c(rbinom(5,1,0.1),rbinom(10,1,0.25),rbinom(10,1,0.75),rbinom(5,1,0.9))

  expect_equal(class(manual_logistic_regression(x, y)), "list")
  expect_equal(round(manual_logistic_regression(x, y)$coefficients[[1]],6), -0.576170)
  expect_equal(round(manual_logistic_regression(x, y)$covariance_matrix[1,1],7), 1.2380262)
  expect_equal(manual_logistic_regression(x, y)$Dispersion, 1)
  expect_equal(round(manual_logistic_regression(x, y)$standard_error[[1]],6), 1.112666)
  expect_equal(round(manual_logistic_regression(x, y)$t_statistics[[1]],3), -0.518)
  expect_equal(round(manual_logistic_regression(x, y)$p_value[[1]],3), 0.605)
  expect_equal(round(manual_logistic_regression(x, y)$deviance_residuals[[1]],7), -0.9638035)
  expect_equal(round(manual_logistic_regression(x, y)$quantile_deviance_residuals[1],4), -1.1308)
  expect_equal(manual_logistic_regression(x, y)$Null_deviance_degrees_of_freedom, 29)
  expect_equal(manual_logistic_regression(x, y)$Residual_deviance_degrees_of_freedom, 26)
  expect_equal(round(manual_logistic_regression(x, y)$Null_deviance,4), 40.3807)
  expect_equal(round(manual_logistic_regression(x, y)$Residual_deviance,5), 40.15877)
  expect_equal(round(manual_logistic_regression(x, y)$AIC, 3), 48.159)
})
